"""updated user

Revision ID: bf8c233ba19b
Revises: fead45cfd6c4
Create Date: 2025-11-21 17:08:30.325699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8c233ba19b'
down_revision = 'fead45cfd6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('migraine_days_per_month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trigger_stress', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trigger_hormones', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trigger_sleep', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trigger_weather', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trigger_meals', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('trigger_medicine', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('normal_sleep', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('normal_sleep')
        batch_op.drop_column('trigger_medicine')
        batch_op.drop_column('trigger_meals')
        batch_op.drop_column('trigger_weather')
        batch_op.drop_column('trigger_sleep')
        batch_op.drop_column('trigger_hormones')
        batch_op.drop_column('trigger_stress')
        batch_op.drop_column('migraine_days_per_month')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
